# Generated by Django 6.0.1 on 2026-01-26 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='last_ten_tests_word_count',
            new_name='last_ten_tests_char_count',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='lifetime_word_count',
            new_name='lifetime_char_count',
        ),
    ]
