# Generated by Django 5.2.7 on 2025-11-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avg_wpm',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='best_wpm',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
