# Generated by Django 6.0.1 on 2026-01-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_rename_last_ten_tests_word_count_customuser_last_ten_tests_char_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='wpm_log',
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_list',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wpm_list',
            field=models.JSONField(default=list),
        ),
    ]
